In [1]:
from google.colab import drive
drive.mount('/content/drive')

import sys
# Append the directory to your python path using sys
sys.path.append('/content/drive/MyDrive/TESIS GRAF/UTAMA/KOMPUTASI')
# Import the module
import Loc_Col_dsatur, Loc_Col_greedy

Mounted at /content/drive


ALGORITMA GREEDY

In [2]:
from os import wait
import networkx as nx
import numpy as np
import Loc_Col_greedy as lcgd
import time

a = 1
b = 1
m = 10
n = 10
indeks_a = []
indeks_b = []
for i in range(a,m+1):
  indeks_a.append(i)
for i in range(b,n+1):
  indeks_b.append(i)
PK = np.zeros((m,n))
PKL = np.zeros((m,n))
for i,v in enumerate(indeks_a):
  for j,w in enumerate(indeks_b):
     if v < 3 and w < 3 :
        PK[i][j] = 0
        PKL[i][j] = 0
     if v >= 3 and w >= 3 :
        P = nx.path_graph(v)
        K = nx.complete_graph(w)
        pk_kai, pk_kaiL = lcgd.greedy(P,K)
        PK[i][j] = pk_kai
        PKL[i][j] = pk_kaiL
print("PKL = k Pewarnaan Lokasi P tensor K")
print(indeks_b)
print(PKL)
print("PK = k Pewarnaan Jarak 2 P tensor K")
print(indeks_b)
print(PK)

PKL = k Pewarnaan Lokasi P tensor K
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
PK = k Pewarnaan Jarak 2 P tensor K
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]]


ALGORITMA DSATUR

In [3]:
from os import wait
import networkx as nx
import numpy as np
import Loc_Col_dsatur as lcds
import time

a = 1
b = 1
m = 10
n = 10
indeks_a = []
indeks_b = []
for i in range(a,m+1):
  indeks_a.append(i)
for i in range(b,n+1):
  indeks_b.append(i)
PK = np.zeros((m,n))
PKL = np.zeros((m,n))
for i,v in enumerate(indeks_a):
  for j,w in enumerate(indeks_b):
     if v < 3 and w < 3 :
        PK[i][j] = 0
        PKL[i][j] = 0
     if v >= 3 and w >= 3 :
        P = nx.path_graph(v)
        K = nx.complete_graph(w)
        pk_kai, pk_kaiL = lcds.dsatur(P,K)
        PK[i][j] = pk_kai
        PKL[i][j] = pk_kaiL
print(indeks_b)
print(PKL)
print(indeks_b)
print(PK)
print(indeks_b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 0.  0.  6.  8. 10. 12. 14. 16. 18. 20.]]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
